import type { ItemDefinition } from '@/game/models/item'

/** 物品品质显示色（供 UI 使用） */
export const ITEM_QUALITY_COLOR: Record<ItemDefinition['quality'], string> = {
  凡品: '#9a9590',
  黄品: '#c9a227',
  玄品: '#4a9ec9',
  地品: '#9b59b6',
  天品: '#e67e22',
  仙品: '#4ac97a',
  神品: '#ff6b6b',
}

/** 物品模板表 */
export const ITEM_DEFINITIONS: ItemDefinition[] = [
  {
    id: 'item_julingcao',
    name: '聚灵草',
    description: '常见灵草，坊市可收购。',
    category: 'material',
    quality: '凡品',
    maxStack: 999,
    sellPrice: 15,
  },
  {
    id: 'item_lingshi_suipian',
    name: '灵石碎片',
    description: '破碎的灵石，可熔炼或出售。',
    category: 'material',
    quality: '凡品',
    maxStack: 999,
    sellPrice: 5,
  },
  {
    id: 'item_yaodan_canque',
    name: '妖丹残片',
    description: '妖兽体内凝结的丹核碎片，炼器材料。',
    category: 'material',
    quality: '黄品',
    maxStack: 99,
    sellPrice: 60,
  },
  {
    id: 'item_dongfu_treasure_02',
    name: '清幽灵砂',
    description: '蕴含地脉清气，可助洞府升格为清幽洞府。历练极低概率掉落，坊市偶现寄售。',
    category: 'treasure',
    quality: '黄品',
    maxStack: 10,
    sellPrice: 0,
  },
  {
    id: 'item_dongfu_treasure_03',
    name: '凝气灵珠',
    description: '凝聚天地灵气而成，可助洞府升格为灵气洞府。',
    category: 'treasure',
    quality: '黄品',
    maxStack: 10,
    sellPrice: 0,
  },
  {
    id: 'item_dongfu_treasure_04',
    name: '地脉碎晶',
    description: '地脉深处采出的碎晶，可助洞府升格为聚灵洞府。',
    category: 'treasure',
    quality: '玄品',
    maxStack: 10,
    sellPrice: 0,
  },
  {
    id: 'item_dongfu_treasure_05',
    name: '仙霞石髓',
    description: '仙霞凝成的石髓，可助洞府升格为仙家洞府。',
    category: 'treasure',
    quality: '玄品',
    maxStack: 10,
    sellPrice: 0,
  },
  {
    id: 'item_dongfu_treasure_06',
    name: '福地符胚',
    description: '上古福地残留的符胚，可开辟福地洞天。',
    category: 'treasure',
    quality: '地品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_dongfu_treasure_07',
    name: '灵脉芯核',
    description: '截取自灵脉的芯核，可筑灵脉洞府。',
    category: 'treasure',
    quality: '地品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_dongfu_treasure_08',
    name: '九天云泥',
    description: '九天之上坠落的云泥，可铸仙府根基。',
    category: 'treasure',
    quality: '天品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_dongfu_treasure_09',
    name: '洞天本源',
    description: '洞天福地的一缕本源，可升格洞天福地。',
    category: 'treasure',
    quality: '天品',
    maxStack: 3,
    sellPrice: 0,
  },
  {
    id: 'item_dongfu_treasure_10',
    name: '混沌仙核',
    description: '混沌中孕育的仙核，可成就无上仙府。',
    category: 'treasure',
    quality: '仙品',
    maxStack: 3,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_blueprint_01',
    name: '一品聚灵阵图纸',
    description: '记载一品聚灵阵的布阵要诀，参悟后可布阵。',
    category: 'material',
    quality: '黄品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_blueprint_02',
    name: '二品聚灵阵图纸',
    description: '记载二品聚灵阵的布阵要诀，参悟后可升阵。',
    category: 'material',
    quality: '黄品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_blueprint_03',
    name: '三品聚灵阵图纸',
    description: '记载三品聚灵阵的布阵要诀，参悟后可升阵。',
    category: 'material',
    quality: '玄品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_blueprint_04',
    name: '四品聚灵阵图纸',
    description: '记载四品聚灵阵的布阵要诀，参悟后可升阵。',
    category: 'material',
    quality: '地品',
    maxStack: 3,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_blueprint_05',
    name: '五品聚灵阵图纸',
    description: '记载五品聚灵阵的布阵要诀，参悟后可升阵。',
    category: 'material',
    quality: '天品',
    maxStack: 3,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_treasure_01',
    name: '阵基灵砂',
    description: '布阵基座所用灵砂，可助布置一品聚灵阵。',
    category: 'treasure',
    quality: '黄品',
    maxStack: 10,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_treasure_02',
    name: '阵眼灵晶',
    description: '凝聚阵眼之力的灵晶，可助布置二品聚灵阵。',
    category: 'treasure',
    quality: '黄品',
    maxStack: 10,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_treasure_03',
    name: '聚灵阵盘',
    description: '刻录聚灵符文的阵盘，可助布置三品聚灵阵。',
    category: 'treasure',
    quality: '玄品',
    maxStack: 10,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_treasure_04',
    name: '玄阵枢核',
    description: '玄妙阵枢的核心，可助布置四品聚灵阵。',
    category: 'treasure',
    quality: '地品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_zhenfa_treasure_05',
    name: '天阵本源',
    description: '天阵运转的一缕本源，可助布置五品聚灵阵。',
    category: 'treasure',
    quality: '天品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_fabao_material_lingwen',
    name: '灵纹碎片',
    description: '刻有残缺灵纹的碎片，炼器常用材料。',
    category: 'material',
    quality: '凡品',
    maxStack: 999,
    sellPrice: 20,
  },
  {
    id: 'item_fabao_material_chiyan',
    name: '赤焰精魄',
    description: '赤焰凝成的精魄，中品攻击法器炼制材料。',
    category: 'material',
    quality: '黄品',
    maxStack: 99,
    sellPrice: 80,
  },
  {
    id: 'item_fabao_material_zixiao',
    name: '紫霄雷砂',
    description: '蕴含紫霄雷力的砂粒，上品攻击法器炼制材料。',
    category: 'material',
    quality: '玄品',
    maxStack: 50,
    sellPrice: 200,
  },
  {
    id: 'item_fabao_material_xuanwu',
    name: '玄武鳞粉',
    description: '玄武鳞甲磨制的粉末，中品防御法器炼制材料。',
    category: 'material',
    quality: '黄品',
    maxStack: 99,
    sellPrice: 80,
  },
  {
    id: 'item_fabao_material_taixu',
    name: '太虚云气',
    description: '太虚之气凝成的云气，上品防御法器炼制材料。',
    category: 'material',
    quality: '玄品',
    maxStack: 50,
    sellPrice: 200,
  },
  {
    id: 'item_fabao_blueprint_attack_lower',
    name: '下品攻击法器图纸',
    description: '记载玄铁短刃炼制要诀，参悟后可在洞府炼器台炼制。',
    category: 'material',
    quality: '黄品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_fabao_blueprint_attack_mid',
    name: '中品攻击法器图纸',
    description: '记载赤焰飞剑炼制要诀，参悟后可在洞府炼器台炼制。',
    category: 'material',
    quality: '玄品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_fabao_blueprint_attack_high',
    name: '上品攻击法器图纸',
    description: '记载紫霄神雷珠炼制要诀，参悟后可在洞府炼器台炼制。',
    category: 'material',
    quality: '地品',
    maxStack: 3,
    sellPrice: 0,
  },
  {
    id: 'item_fabao_blueprint_defense_lower',
    name: '下品防御法器图纸',
    description: '记载青玉护符炼制要诀，参悟后可在洞府炼器台炼制。',
    category: 'material',
    quality: '黄品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_fabao_blueprint_defense_mid',
    name: '中品防御法器图纸',
    description: '记载玄武甲片炼制要诀，参悟后可在洞府炼器台炼制。',
    category: 'material',
    quality: '玄品',
    maxStack: 5,
    sellPrice: 0,
  },
  {
    id: 'item_fabao_blueprint_defense_high',
    name: '上品防御法器图纸',
    description: '记载太虚灵盾炼制要诀，参悟后可在洞府炼器台炼制。',
    category: 'material',
    quality: '地品',
    maxStack: 3,
    sellPrice: 0,
  },
]

const itemMap = new Map(ITEM_DEFINITIONS.map((item) => [item.id, item]))

/**
 * 按 id 获取物品模板
 */
export function getItemDefinition(itemId: string): ItemDefinition | undefined {
  return itemMap.get(itemId)
}

/**
 * 获取全部物品模板
 */
export function getAllItemDefinitions(): ItemDefinition[] {
  return ITEM_DEFINITIONS
}
